package com.udid.utilities

object AppConstants {
    const val ITEM="ITEM"
    const val OTP="OTP"
    const val DATE_OF_BIRTH="DATE_OF_BIRTH"
    const val APPLICATION_NUMBER="APPLICATION_NUMBER"
    const val WALK_THROUGH="WALK_THROUGH"
    const val STATUS_NAME="STATUSNAME"
    const val PHONE_NUMBER = "PHONE_NUMBER"
    const val OFFICE_PHONE_NUMBER = "OFFICE_PHONE_NUMBER"
    const val OFFICE_ADDRESS = "OFFICE_ADDRESS"
    const val COUNTRY_CODE = "COUNTRY_CODE"
    const val USER_ID = "USER_ID"
    const val USER_TYPE = "USER_TYPE"
    const val USERID = "USERID"
    const val CATEGORY_ID = "CATEGORY_ID"
    const val FULL_NAME = "FULL_NAME"

    const val IS_FROM = "IS_FROM"
    const val EMAIL = "EMAIL"

    // const val APPLE = "Apple"
    const val ADDRESS = "ADDRESS"
    const val PROFILE_COMPLETED = "PROFILE_COMPLETED"
    const val PROFILE = "PROFILE"
    const val PENSION_CALCULATOR = "PENSION_CALCULATOR"
    const val COUNTRIES = "COUNTRIES"
    const val CATEGORIES = "CATEGORIES"
    const val MISSED_CALL = "MISSED_CALL"
    const val REJECT_CALL = "REJECT_CALL"
    const val BLOCKED = "BLOCKED"

    // const val FACEBOOK = "Facebook"
    const val USER_NAME = "USER_NAME"
    const val SOCKET_BASE_URL = ""
    const val SOCKET_TAG = "<<<<<SOCKET>>>>>"
    const val SOCKET_CONNECT = "SOCKET_CONNECT"
    const val SOCKET_INIT = "init"
    const val ACKREQUEST: String = "<<<ACKREQUEST>>>"
    const val ANDROID = "android"
    const val CALL = "CALL"
    const val CHAT = "CHAT"
    const val TERMS_AND_COND_URL = ""
    const val PRIVACY_POLICY_URL = "PRIVACY_POLICY_URL"
    const val SUBSCRIPTION_DETAILS_URL = ""
    const val NOT_FROM_SETTINGS = "NOT_FROM_SETTINGS"
    const val YES = "YES"
    const val NO = "NO"
    const val FROM = "FROM"
    const val PROFILE_IMAGE = "PROFILE_IMAGE"

    const val FIREBASE_DEVICE_TOKEN = "firebase_device_token"

    const val LOCALE = "LOCALE"

    const val TEXT: String = "TEXT"
    const val IMAGE: String = "IMAGE"
    const val MEM_ADD_REM: String = "MEM_ADD_REM"
    const val VIDEO: String = "VIDEO"
    const val AUDIO: String = "AUDIO"

    const val fullName: String = "fullName"
    const val photo: String = "photo"
    const val OTHER: String = "Other"

}